### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by am610** [CosmicFish/CosmicFish#26]
I am trying to install it on my mac, OsX 10.15.xx

`pip install cosmicfish`

then in the directory, I do `make cosmicfish`

I get errors : 

 constants.f90 -o cosmicfish_build/constants.o
constants.f90:84:30:

```
   84 |         if (id==0) error stop('Error id must be non-zero')
      |                              1
Error: Blank required in ERROR STOP statement near (1)
make[1]: *** [cosmicfish_build/constants.o] Error 1
make: *** [camb] Error 2

I have gfortran loaded, when doing `which gfortran`

I get 
`/usr/local/bin/gfortran
`
```

**Comment by mraveri** [comment]
Hi @am610 which version of gfortran are you using?

Cosmicfish is not pip-installable so you should compile from source downloading it from here. Does the problem persist?

**Comment by am610** [comment]
Works perfect.
